# Configuration file for FindDeathLocation

# The item which can be used to find your last death location
# must be an item ID, by default 288, a feather
# requires permission: finddeathlocation.item
# default: item: 288
item: 288

# When players teleport to a death location,
# how many blocks above should they teleport?
# This is to prevent accidentally picking up a players items
# by default 0, meaning you will pick up any nearby items
# 1 works well to avoid picking up items
# default: numBlocksAbove: 0
numBlocksAbove: 0

# Language
notpermitted: '&cYou are not permitted to do this!'
notdied: '&cYou have not yet died!'
anotherworld: '&cYour death location is in another world!'
noconsole: '&cConsole cannot run FindDeathLocation commands!'
noplayer: '&cPlease specify a player!'
nolocation: '&cPlayer death location not found!'