# Configuration file for FindDeathLocation

# The item which can be used to find your last death location
# must be an item ID, by default 288, a feather
# requires permission: finddeathlocation.item
# default: item: 288
item: 288

# Which mouse button should the above item use?
# it is possible to use both here, if desired
# default: leftClick: true
# default: rightClick: false
leftClick: true
rightClick: false

# Should players be given the item when they respawn?
# default: itemOnRespawn: false
itemOnRespawn: false

# Should compasses point to players last death locations?
# If you would also like players to click with a compass for distance,
# then change the "item" above to be a compass, item ID 345 
# default: compassDirection: false
compassDirection: false

# Should distances be calculated in 3 dimensions instead of 2?
# in other words, should height count towards distance?
# default: distance3D: false
distance3D: false

# The time, in seconds, to wait before teleporting to a players death location
# can be bypassed with the permission finddeathlocation.tp.bypass
# or set to 0 to disable completely
# default: delaySeconds: 5
delaySeconds: 5

# The time, in seconds, before a player can use /tpdeath or /tpdeath <player>
# can be bypassed with the permission finddeathlocation.tp.bypass
# or set to 0 to disable completely
# default: cooldownSeconds: 3600
cooldownSeconds: 3600

# When players teleport to a death location,
# how many blocks above should they teleport?
# This is to prevent accidentally picking up a players items
# by default 0, meaning you will pick up any nearby items
# 1 works well to avoid picking up items
# default: numBlocksAbove: 0
numBlocksAbove: 0

# Whether the console should log players death locations.
# default: consoleLog: true
consoleLog: true

# Language
# for senddistance, place the variable "{DISTANCE}" where you would like the distance
# default: senddistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
sendDistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
# for teleporting, place the variable "{DELAY}" where you would like the delay time
# default: teleporting: '&7Teleporting in {DELAY} seconds...'
teleporting: '&7Teleporting in {DELAY} seconds...'
# for cooldown, place the variable "{COOLDOWN}" where you would like the cooldown time
# default: cooldown: '&7You must wait {COOLDOWN}.'
cooldown: '&7You must wait {COOLDOWN}.'
# for deathlog, place the variables "{PLAYER}", "{LOCATION}", and "{WORLD}" where you'd like
# default: deathlog: '{PLAYER} has died at {LOCATION} in {WORLD}.'
deathLog: '&7{PLAYER} has died at &6{LOCATION} &7in {WORLD}.'
notPermitted: '&cYou are not permitted to do this!'
notDied: '&cYou have not yet died!'
anotherWorld: '&cYour death location is in another world!'
tpWait: '&cYou are already teleporting!'
noConsole: '&cConsole cannot run FindDeathLocation commands!'
noLocation: '&cPlayer death location not found!'

# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/FindDeathLocation
# default: metrics: true
metrics: true