# Configuration file for FindDeathLocation

# The item which can be used to find your last death location
# must be an item ID, by default 288, a feather
# requires permission: finddeathlocation.item
# default: item: 288
item: 288

# Which mouse button should the above item use?
# it is possible to use both here, if desired
# default: leftClick: true
# default: rightClick: false
leftClick: true
rightClick: false

# The time, in seconds, to wait before teleporting to a players death location
# can be bypassed with the permission finddeathlocation.tp.bypass
# default: delaySeconds: 5
delaySeconds: 5

# When players teleport to a death location,
# how many blocks above should they teleport?
# This is to prevent accidentally picking up a players items
# by default 0, meaning you will pick up any nearby items
# 1 works well to avoid picking up items
# default: numBlocksAbove: 0
numBlocksAbove: 0

# Language
# for senddistance, place the variable "{DISTANCE}" where you would like the distance
# default: senddistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
senddistance: '&7Your last death is &6{DISTANCE} &7blocks away.'
# for teleporting, place the variable "{DELAY}" where you would like the delay time
# default: teleporting: '&7Teleporting in {DELAY} seconds...'
teleporting: '&7Teleporting in {DELAY} seconds...'
notpermitted: '&cYou are not permitted to do this!'
notdied: '&cYou have not yet died!'
anotherworld: '&cYour death location is in another world!'
noconsole: '&cConsole cannot run FindDeathLocation commands!'
nolocation: '&cPlayer death location not found!'

# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/FindDeathLocation
# default: metrics: true
metrics: true