name: FindDeathLocation
version: 1.4.0
main: me.kevinnovak.finddeathlocation.FindDeathLocation
author: KevinNovak
description: Finds players death location!

commands:
    finddeath:
        usage: /<command>
        description: Finds distance to players death location.
    tpdeath:
        usage: /<command>
        description: Teleports to a players death location.
        
permissions:
    finddeathlocation.item:
        description: Use the find death item.
        default: op
    finddeathlocation.command:
        description: Use the find death command.
        default: op
    finddeathlocation.tp:
        description: Teleport to your death location.
        default: op
    finddeathlocation.tp.others:
        description: Teleport to a players death location.
        default: op
    finddeathlocation.tp.bypass:
        description: Bypass the teleportation delay.
        default: op
    finddeathlocation.log:
        description: See death locations when players die.
        default: false